FROM node:21-alpine
WORKDIR /app
COPY ./notgpt-cli/package.json .
RUN yarn install --production
COPY ./notgpt-cli/ .
RUN yarn add typescript tsc ts-node && yarn build
CMD ["yarn", "run", "preview"]
EXPOSE 80